<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>11</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AngleSharp" Version="1.0.4" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="7.0.0" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="7.0.1" />
      <PackageReference Include="Serilog" Version="3.0.1" />
      <PackageReference Include="Serilog.AspNetCore" Version="7.0.0" />
      <PackageReference Include="Serilog.Sinks.Console" Version="4.1.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Dictionary.Contacts\Dictionary.Contacts.csproj" />
      <ProjectReference Include="..\Dictionary.Data\Dictionary.Data.csproj" />
    </ItemGroup>

</Project>
