// <auto-generated />
using Dictionary.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dictionary.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230716134742_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dictionary.Data.Models.PossibleTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Example")
                        .HasColumnType("text")
                        .HasColumnName("example");

                    b.Property<string>("Explanation")
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<string>("Translation")
                        .HasColumnType("text")
                        .HasColumnName("translation");

                    b.Property<int>("WordId")
                        .HasColumnType("integer")
                        .HasColumnName("word_id");

                    b.HasKey("Id")
                        .HasName("pk_possible_translations");

                    b.HasIndex("Example")
                        .HasDatabaseName("ix_possible_translations_example");

                    b.HasIndex("Explanation")
                        .HasDatabaseName("ix_possible_translations_explanation");

                    b.HasIndex("Translation")
                        .HasDatabaseName("ix_possible_translations_translation");

                    b.HasIndex("WordId")
                        .HasDatabaseName("ix_possible_translations_word_id");

                    b.ToTable("possible_translations", (string)null);
                });

            modelBuilder.Entity("Dictionary.Data.Models.Relation", b =>
                {
                    b.Property<int>("WordId")
                        .HasColumnType("integer")
                        .HasColumnName("word_id");

                    b.Property<int>("RelatedWordId")
                        .HasColumnType("integer")
                        .HasColumnName("related_word_id");

                    b.HasKey("WordId", "RelatedWordId")
                        .HasName("pk_relations");

                    b.HasIndex("RelatedWordId")
                        .HasDatabaseName("ix_relations_related_word_id");

                    b.ToTable("relations", (string)null);
                });

            modelBuilder.Entity("Dictionary.Data.Models.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_words");

                    b.ToTable("words", (string)null);
                });

            modelBuilder.Entity("Dictionary.Data.Models.PossibleTranslation", b =>
                {
                    b.HasOne("Dictionary.Data.Models.Word", "Word")
                        .WithMany("PossibleTranslations")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_possible_translations_words_word_id");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("Dictionary.Data.Models.Relation", b =>
                {
                    b.HasOne("Dictionary.Data.Models.Word", "RelatedWord")
                        .WithMany("RelatedFromWords")
                        .HasForeignKey("RelatedWordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_relations_words_related_word_id");

                    b.HasOne("Dictionary.Data.Models.Word", "Word")
                        .WithMany("RelatedWords")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_relations_words_word_id");

                    b.Navigation("RelatedWord");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("Dictionary.Data.Models.Word", b =>
                {
                    b.Navigation("PossibleTranslations");

                    b.Navigation("RelatedFromWords");

                    b.Navigation("RelatedWords");
                });
#pragma warning restore 612, 618
        }
    }
}
