// <auto-generated />
using Dictionary.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dictionary.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dictionary.Data.Models.Example", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PossibleTranslationId")
                        .HasColumnType("integer")
                        .HasColumnName("possible_translation_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_examples");

                    b.HasIndex("PossibleTranslationId")
                        .HasDatabaseName("ix_examples_possible_translation_id");

                    b.HasIndex("Value")
                        .HasDatabaseName("ix_examples_value");

                    b.ToTable("examples", (string)null);
                });

            modelBuilder.Entity("Dictionary.Data.Models.PossibleTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Explanation")
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<string>("Translation")
                        .HasColumnType("text")
                        .HasColumnName("translation");

                    b.Property<int>("WordId")
                        .HasColumnType("integer")
                        .HasColumnName("word_id");

                    b.HasKey("Id")
                        .HasName("pk_possible_translations");

                    b.HasIndex("Explanation")
                        .HasDatabaseName("ix_possible_translations_explanation");

                    b.HasIndex("Translation")
                        .HasDatabaseName("ix_possible_translations_translation");

                    b.HasIndex("WordId")
                        .HasDatabaseName("ix_possible_translations_word_id");

                    b.ToTable("possible_translations", (string)null);
                });

            modelBuilder.Entity("Dictionary.Data.Models.Relation", b =>
                {
                    b.Property<int>("WordId")
                        .HasColumnType("integer")
                        .HasColumnName("word_id");

                    b.Property<int>("RelatedWordId")
                        .HasColumnType("integer")
                        .HasColumnName("related_word_id");

                    b.HasKey("WordId", "RelatedWordId")
                        .HasName("pk_relations");

                    b.HasIndex("RelatedWordId")
                        .HasDatabaseName("ix_relations_related_word_id");

                    b.ToTable("relations", (string)null);
                });

            modelBuilder.Entity("Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LanguagePart")
                        .HasColumnType("text")
                        .HasColumnName("language_part");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_words");

                    b.HasIndex("LanguagePart")
                        .HasDatabaseName("ix_words_language_part");

                    b.HasIndex("Value")
                        .HasDatabaseName("ix_words_value");

                    b.HasIndex("LanguagePart", "Value")
                        .IsUnique()
                        .HasDatabaseName("ix_words_language_part_value");

                    b.ToTable("words", (string)null);
                });

            modelBuilder.Entity("Dictionary.Data.Models.Example", b =>
                {
                    b.HasOne("Dictionary.Data.Models.PossibleTranslation", "PossibleTranslation")
                        .WithMany("Examples")
                        .HasForeignKey("PossibleTranslationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_examples_possible_translations_possible_translation_id");

                    b.Navigation("PossibleTranslation");
                });

            modelBuilder.Entity("Dictionary.Data.Models.PossibleTranslation", b =>
                {
                    b.HasOne("Word", "Word")
                        .WithMany("PossibleTranslations")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_possible_translations_words_word_id");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("Dictionary.Data.Models.Relation", b =>
                {
                    b.HasOne("Word", "RelatedWord")
                        .WithMany("RelatedFromWords")
                        .HasForeignKey("RelatedWordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_relations_words_related_word_id");

                    b.HasOne("Word", "Word")
                        .WithMany("RelatedWords")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_relations_words_word_id");

                    b.Navigation("RelatedWord");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("Dictionary.Data.Models.PossibleTranslation", b =>
                {
                    b.Navigation("Examples");
                });

            modelBuilder.Entity("Word", b =>
                {
                    b.Navigation("PossibleTranslations");

                    b.Navigation("RelatedFromWords");

                    b.Navigation("RelatedWords");
                });
#pragma warning restore 612, 618
        }
    }
}
